#declare your layouts here
layout:
  #This one if none declared later
  default: layout.php
  
  #key is module/action
  #mod/act: layout-other.php
  
  #For actions without a layout (still can have a view)
  #mod2/act2: none
  
meta:
  #If not set, default is utf-8
  #charset: utf-8
  
  #Default title here
  #title: My Website rox teh clox
    
  